[phases.setup]
aptPkgs = ["gcc", "postgresql-client"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python main.py" 